#' A sample covariance matrix for rheumatoid arthritis
#'
#' A covariance matrix of rheumatoid arthritis (RA) related feature counts (after log transformation). Must have colnames and rownames.
#'
#' @docType data
#' @keywords datasets
#' @name cov_RA
#' @usage data(cov_RA)
#' @format A numeric matrix with 53 rows and 53 columns
NULL



#' Codified features related to rheumatoid arthritis
#'
#' A dataframe containing codified features related to rheumatoid disease (PheCode:714.1) generated by ONCE. The variables are as follows:
#'
#' \itemize{
#'   \item Variable. codified feature id (possible categories: PheCode/RXNORM/CCS/LOINC/Other lab)
#'   \item Description. full feature description
#'   \item cos. Cosine similarity between the feature and PheCode:714.1.
#'   \item select. Selected features with \code{cos}> mode(cos) + 2 * median absolute deviation(cos)
#'   \item ...
#' }
#'
#' @docType data
#' @keywords datasets
#' @name codify_RA
#' @usage data(codify_RA)
#' @format A data frame with 78 rows and 10 variables
NULL



#' NLP features related to rheumatoid arthritis
#'
#' A dataframe containing NLP features related to rheumatoid disease (C0003873) generated by ONCE. The variables are as follows:
#'
#' \itemize{
#'   \item cui. NLP feature id (possible categories: CUI)
#'   \item term. full feature description
#'   \item cos_cui. cosine similarity between the feature and C0003873
#'   \item article_count. the number of related articles containing the feature
#'   \item mgb_freq term-level frequency in the MGB patient cohort
#'   \item Acos_Ccos_d_log_va_plus. Weight combining \code{cos_cui}, \code{article_count} and \code{mgb_freq} showing relatedness between features and C0003873
#'   \item select. Selected features with \code{Acos_Ccos_d_log_va_plus}> mode(Acos_Ccos_d_log_va_plus) + 2 * median absolute deviation(Acos_Ccos_d_log_va_plus)
#'   \item ...
#' }
#'
#' @docType data
#' @keywords datasets
#' @name cui_RA
#' @usage data(cui_RA)
#' @format A data frame with 1183 rows and 13 variables
NULL



#' Dictionary mapping feature id to feature description
#'
#' A dataframe containing id and description of features appearing in \code{input.cov}, \code{codify.feature} and \code{cuisearch.feature}. The variables are as follows:
#'
#' \itemize{
#'   \item Variable. feature id (possible categories: PheCode/CCS/LOINC/RXNORM/CUI)
#'   \item Description. full feature description
#' }
#'
#' @docType data
#' @keywords datasets
#' @name dict_RA
#' @usage data(dict_RA)
#' @format A data frame with 52 rows and 2 variables
NULL


#' Pseudo-individual data for score prediction and model evaluation
#'
#' A dataframe containing pseudo patient id and codified and NLP feature counts (after log transformation). The variables are as follows:
#'
#' \itemize{
#'   \item patient_num unique patient id (pseudo)
#'   \item utl health utility score
#'   \item ... Codified and NLP features
#' }
#'
#' @docType data
#' @keywords datasets
#' @name dat_part
#' @usage data(dat_part)
#' @format A data frame with 153 rows and 54 variables
NULL



#' Pseudo-individual data with gold label for model evaluation
#'
#' A dataframe containing pseudo patient id and pseudo gold label (possibly also sample probability). The variables are as follows:
#'
#' \itemize{
#'   \item patient_num unique patient id (pseudo)
#'   \item pi sample probability (can be \code{NULL} if uniformly sampled)
#'   \item Y gold label (pseudo)
#' }
#'
#' @docType data
#' @keywords datasets
#' @name gold_label
#' @usage data(gold_label)
#' @format A data frame with 153 rows and 3 variables
NULL


#' Conditional feature mean vector (Y=0)
#'
#' A named numeric vector containing the mean of log(feature count) given negative labels for RA disease(Y=0).
#'
#' @docType data
#' @keywords datasets
#' @name mu0
#' @usage data(mu0)
#' @format A named vector with 40 entries.
NULL


#' Conditional feature mean vector (Y=1)
#'
#' A named numeric vector containing the mean of log(feature count) given positive labels for RA disease(Y=1).
#'
#' @docType data
#' @keywords datasets
#' @name mu1
#' @usage data(mu1)
#' @format A named vector with 40 entries.
NULL


#' Conditional feature covariance matrix (Y=0)
#'
#' A numeric covariance matrix of log(feature count) given negative labels for RA disease(Y=0). Must have colnames and rownames.
#'
#' @docType data
#' @keywords datasets
#' @name var0
#' @usage data(var0)
#' @format A 40*40 covariance matrix.
NULL


#' Conditional feature covariance matrix (Y=1)
#'
#' A numeric covariance matrix of log(feature count) given positive labels for RA disease(Y=1). Must have colnames and rownames.
#'
#' @docType data
#' @keywords datasets
#' @name var1
#' @usage data(var1)
#' @format A 40*40 covariance matrix.
NULL


#' Prevalence of PheCode714.1
#'
#' A number indicating the prevalence of RA disease in the pseudo-population.
#'
#' @docType data
#' @keywords datasets
#' @name prev_Y
#' @usage data(prev_Y)
#' @format A number.
NULL
